
<link rel="stylesheet" type="text/css" href="{{ asset('public/templates/admin/assets/css/reporting.css') }}"/>
<h4>@lang('main.sales.title')</h4>
<div class="vItems">
    <table class="table table-bordered" cellspacing="0">
        <tr>
            <td>@lang('main.sales.field.invoice_number')</td>
            <td>{{$sales->invoice_number}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.invoice_date')</td>
            <td>{{$sales->invoice_date}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.customer_account')</td>
            <td>{{$sales->customer_account}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.customer_name')</td>
            <td>{{$sales->customer_name}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.address1')</td>
            <td>{{$sales->address1}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.address2')</td>
            <td>{{$sales->address2}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.town')</td>
            <td>{{$sales->town}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.country')</td>
            <td>{{$sales->country}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.postcode')</td>
            <td>{{$sales->postcode}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.spacer1')</td>
            <td>{{$sales->spacer1}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.customer_account2')</td>
            <td>{{$sales->customer_account2}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.numb1')</td>
            <td>{{$sales->numb1}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.items')</td>
            <td>{{$sales->items}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.weight')</td>
            <td>{{$sales->weight}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.invoice_total')</td>
            <td>{{$sales->invoice_total}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.numb2')</td>
            <td>{{$sales->numb2}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.spacer2')</td>
            <td>{{$sales->spacer2}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.job_number')</td>
            <td>{{$sales->job_number}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.job_date')</td>
            <td>{{$sales->job_date}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.sending_deport')</td>
            <td>{{$sales->sending_deport}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.delivery_deport')</td>
            <td>{{$sales->delivery_deport}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.destination')</td>
            <td>{{$sales->destination}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.town2')</td>
            <td>{{$sales->town2}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.postcode2')</td>
            <td>{{$sales->postcode2}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.service_type')</td>
            <td>{{$sales->service_type}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.items2')</td>
            <td>{{$sales->items2}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.volume_weight')</td>
            <td>{{$sales->volume_weight}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.numb3')</td>
            <td>{{$sales->numb3}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.increased_liability_cover')</td>
            <td>{{$sales->increased_liability_cover}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.sub_total')</td>
            <td>{{$sales->sub_total}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.spacer3')</td>
            <td>{{$sales->spacer3}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.numb4')</td>
            <td>{{$sales->numb4}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.sender_reference')</td>
            <td>{{$sales->sender_reference}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.numb5')</td>
            <td>{{$sales->numb5}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.percentage_fuel_surcharge')</td>
            <td>{{$sales->percentage_fuel_surcharge}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.spacer4')</td>
            <td>{{$sales->spacer4}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.senders_postcode')</td>
            <td>{{$sales->senders_postcode}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.vat_amount')</td>
            <td>{{$sales->vat_amount}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.vat_percent')</td>
            <td>{{$sales->vat_percent}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.uploadcode')</td>
            <td>{{$sales->uploadcode}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.ms_created')</td>
            <td>{{$sales->ms_created}}</td>
        </tr>
       <tr>
            <td>@lang('main.sales.field.job_dat')</td>
            <td>{{$sales->job_dat}}</td>
        </tr>
       
    </table>
    
</div>

