import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  name: text("name"),
  email: text("email").notNull().unique(),
  password: text("password").notNull(),
  role: text("role").notNull().default("user"),
  username: text("username").unique(),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const customers = sqliteTable("customers", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  customerAccount: text("customer_account").notNull().unique(),
  customerEmail: text("customer_email"),
  customerEmailBcc: text("customer_email_bcc"),
  customerPhone: text("customer_phone"),
  termsOfPayment: text("terms_of_payment"),
  messageType: text("message_type"),
  poNumber: text("po_number"),
  customerMessage: text("customer_message"),
  loginAccess: integer("login_access", { mode: "boolean" }).default(false),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const sales = sqliteTable("sales", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  invoiceNumber: text("invoice_number").notNull(),
  invoiceDate: text("invoice_date"),
  customerAccount: text("customer_account").notNull(),
  customerName: text("customer_name"),
  address1: text("address1"),
  address2: text("address2"),
  town: text("town"),
  country: text("country"),
  postcode: text("postcode"),
  spacer1: text("spacer1"),
  customerAccount2: text("customer_account2"),
  numb1: real("numb1"),
  items: real("items"),
  weight: real("weight"),
  invoiceTotal: real("invoice_total"),
  numb2: real("numb2"),
  spacer2: text("spacer2"),
  jobNumber: text("job_number"),
  jobDate: text("job_date"),
  sendingDepot: text("sending_depot"),
  deliveryDepot: text("delivery_depot"),
  destination: text("destination"),
  town2: text("town2"),
  postcode2: text("postcode2"),
  serviceType: text("service_type"),
  items2: real("items2"),
  volumeWeight: real("volume_weight"),
  numb3: real("numb3"),
  increasedLiabilityCover: real("increased_liability_cover"),
  subTotal: real("sub_total"),
  spacer3: text("spacer3"),
  numb4: real("numb4"),
  senderReference: text("sender_reference"),
  numb5: real("numb5"),
  percentageFuelSurcharge: real("percentage_fuel_surcharge"),
  percentageResourcingSurcharge: real("percentage_resourcing_surcharge"),
  spacer4: text("spacer4"),
  sendersPostcode: text("senders_postcode"),
  vatAmount: real("vat_amount"),
  vatPercent: real("vat_percent"),
  uploadCode: text("upload_code"),
  msCreated: integer("ms_created").default(0),
  invoiceReady: integer("invoice_ready").default(0),
  uploadTs: text("upload_ts"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const invoices = sqliteTable("invoices", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  salesId: integer("sales_id"),
  customerAccount: text("customer_account").notNull(),
  invoiceNumber: text("invoice_number").notNull(),
  invoiceDate: text("invoice_date"),
  dueDate: text("due_date"),
  dateCreated: text("date_created"),
  terms: text("terms"),
  printer: integer("printer").default(0),
  poNumber: text("po_number"),
  num: integer("num"),
  emailStatus: integer("email_status").default(0),
  batchNo: text("batch_no"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const settings = sqliteTable("settings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  companyName: text("company_name"),
  logo: text("logo"),
  companyAddress1: text("company_address1"),
  companyAddress2: text("company_address2"),
  state: text("state"),
  city: text("city"),
  postcode: text("postcode"),
  country: text("country"),
  phone: text("phone"),
  fax: text("fax"),
  cemail: text("cemail"),
  website: text("website"),
  primaryContact: text("primary_contact"),
  baseCurrency: text("base_currency"),
  vatNumber: text("vat_number"),
  invoiceDueDate: integer("invoice_due_date"),
  invoiceDuePaymentBy: text("invoice_due_payment_by"),
  messageTitle: text("message_title"),
  defaultMessage: text("default_message"),
  defaultMessage2: text("default_message2"),
  sendLimit: integer("send_limit").default(50),
  fuelSurchargePercent: real("fuel_surcharge_percent").default(3.5),
  resourcingSurchargePercent: real("resourcing_surcharge_percent").default(0),
  vatPercent: real("vat_percent").default(20),
});

export const uploadedCsv = sqliteTable("uploaded_csv", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  filename: text("filename").notNull(),
  uploadTs: text("upload_ts").notNull(),
  rowCount: integer("row_count").default(0),
  status: text("status").default("uploaded"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const salesArchive = sqliteTable("sales_archive", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  invoiceNumber: text("invoice_number").notNull(),
  invoiceDate: text("invoice_date"),
  customerAccount: text("customer_account").notNull(),
  customerName: text("customer_name"),
  address1: text("address1"),
  address2: text("address2"),
  town: text("town"),
  country: text("country"),
  postcode: text("postcode"),
  jobNumber: text("job_number"),
  jobDate: text("job_date"),
  destination: text("destination"),
  town2: text("town2"),
  postcode2: text("postcode2"),
  serviceType: text("service_type"),
  items2: real("items2"),
  volumeWeight: real("volume_weight"),
  subTotal: real("sub_total"),
  senderReference: text("sender_reference"),
  percentageFuelSurcharge: real("percentage_fuel_surcharge"),
  percentageResourcingSurcharge: real("percentage_resourcing_surcharge"),
  vatAmount: real("vat_amount"),
  vatPercent: real("vat_percent"),
  invoiceTotal: real("invoice_total"),
  archivedAt: integer("archived_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const invoicesArchive = sqliteTable("invoices_archive", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  customerAccount: text("customer_account").notNull(),
  invoiceNumber: text("invoice_number").notNull(),
  invoiceDate: text("invoice_date"),
  dueDate: text("due_date"),
  printer: integer("printer").default(2),
  emailStatus: integer("email_status").default(1),
  archivedAt: integer("archived_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});
